-- DROP DATABASE
--DROP DATABASE IF EXISTS gamers_db;

-- CREATE DATABASE
CREATE DATABASE gamers_db;

USE gamers_db;

CREATE TABLE games (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gameTitle VARCHAR(64) NOT NULL,
    summary VARCHAR(255),
    onlineStatus BOOLEAN,
    singlePlayer BOOLEAN
);

CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50),
    userName VARCHAR(50) NOT NULL,
    passwordHash VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    bio VARCHAR(300) NOT NUll
);