-- ONLY FOR SEEDING GAMES TABLE IN GAMERS_DB --
USE gamers_db;

INSERT INTO games (gameTitle, summary, onlineStatus, singlePlayer)
VALUES ("Minecraft", NULL, true, true),
       ("Red Dead Redemption 2", NULL, true, true),
       ("Fortnite", NULL, true, true),
       ("Call of Duty", NULL, true, true),
       ("Overwatch 2", NULL, true, true),
       ("Counter Strike", NULL, true, true),
       ("Super Smash Brothers", NULL, true, true),
       ("Grand Theft Auto V", NULL, true, true),
       ("Halo Infinite", NULL, true, true),
       ("Apex Legends", NULL, true, false),
       ("Valorant", NULL, true, true),
       ("NBA 2k23", NULL, true, true),
       ("League of Legends", NULL, true, true),
       ("Dead By Daylight", NULL, true, false),
       ("Madden NFL 23", NULL, true, true),
       ("FIFA 23", NULL, true, true),
       ("Gotham Knights", NULL, true, true),
       ("Rocket League", NULL, true, true),
       ("Roblox", NULL, true, true),
       ("World of Warcraft", NULL, true, true),
       ("Destiny 2", NULL, true, true),
       ("Tom Clancy's Rainbow Six Siege", NULL, true, true),
       ("Fall Guys", NULL, true, false),
       ("Escape From Tarkov", NULL, true, false),
       ("Among Us", NULL, true, false),
       ("The Sims", NULL, false, true),
       ("Dota", NULL, true, true),
       ("God of War", NULL, true, true),
       ("Mario Kart", NULL, true, true),
       ("Smite", NULL, true, true),
       ("DayZ", NULL, true, true),
       ("H1z1", NULL, false, true),
       ("PlayerUnknown's Battlegrounds", NULL, true, true),
       ("Fallout", NULL, true, true),
       ("Doom", NULL, true, true),
       ("Sea of Thieves", NULL, true, true),
       ("Tetris", NULL, true, true),
       ("Borderlands 3", NULL, true, true),
       ("Final Fantasy XV", NULL, true, true),
       ("Divinity: Original Sin 2", NULL, true, true),
       ("Assassin's Creed: Valhalla", NULL, true, true),
       ("Return to Monkey Island", NULL, false, true),
       ("Burnout Paradise Remastered", NULL, true, true),
       ("Mega Man 11", NULL, false, true),
       ("Animal Crossing: New Horizons", NULL, true, true),
       ("Thief", NULL, true, true),
       ("SimCity: BuildIt", NULL, true, true),
       ("TItanfall 2", NULL, true, true),
       ("Tony Hawk's Pro Skater 1 + 2", NULL, true, true),
       ("Monster Hunter Rise: Sunbreak", NULL, true, true),
       ("Resident Evil: Village", NULL, true, true),
       ("System Shock", NULL, true, true),
       ("Mortal Kombat 11", NULL, true, true),
       ("Dark Souls: Remastered", NULL, true, true),
       ("fable Fortuna", NULL, true, true),
       ("Spelunky 2", NULL, true, true),
       ("Donkey Kong Country: Tropical Freeze", NULL, false, true),
       ("Tom Clancy's Splinter Cell: Blacklist", NULL, true, true),
       ("Super Mario 3D World + Bowser's Fury", NULL, true, true),
       ("Silent Hill: Ascension", NULL, false, true),
       ("XCOM: Chimera Squad", NULL, false, true),
       ("Control", NULL, false, true),
       ("Shadow of the Tomb Raider", NULL, true, true),
       ("Batman: Arkham Collection", NULL, true, true),
       ("Dishonored: Death of the Outsider", NULL, false, true),
       ("The Witness", NULL, false, true),
       ("Journey", NULL, true, true),
       ("Uncharted: Legacy of Thieves Collection", NULL, false, true),
       ("Hollow Knight", NULL, true, true),
       ("Left 4 Dead 2", NULL, true, true),
       ("Diablo Immortal", NULL, true, false),
       ("Starcraft: Remastered", NULL, true, true),
       ("Star Wars Jedi: Fallen Order", NULL, false, true),
       ("Pokémon Legends: Arceus", NULL, true, true),
       ("Metroid Dread", NULL, false, true),
       ("The Elder Scrolls V: Skyrim", NULL, true, true),
       ("Shadow of the Colossus", NULL, true, true),
       ("The Last of Us 2", NULL, true, true),
       ("Metal Gear Survive", NULL, true, true),
       ("Sid Meier's Civilization VI", NULL, true, true),
       ("The Legend of Zelda: Skyward Sword HD", NULL, true, true),
       ("Half-Life: Alyx", NULL, true, true),
       ("Chrono Trigger", NULL, false, true),
       ("Portal", NULL, true, true),
       ("Street Fighter V: Champion Edition", NULL, true, true),
       ("Undertale", NULL, true, true),
       ("Bloodborne", NULL, true, true),
       ("BioShock: The Collection", NULL, true, true),
       ("The Witcher: Monster Slayer", NULL, false, true),
       ("Castlevania Advance Collection", NULL, true, true),
       ("Hades", NULL, false, true),
       ("Mass Effect Legendary Edition", NULL, false, true),
       ("Need for Speed: Hot Pursuit Remastered", NULL, true, true),
       ("Midnight Club: Los Angeles Complete Edition", NULL, true, true),
       ("The Lord of the Rings: Gollum", NULL, false, true),
       ("Cyberpunk 2077", NULL, true, true),
       ("Guitar Hero Live", NULL, true, true),
       ("Forza Horizon 5", NULL, true, true),
       ("Far Cry 6", NULL, true, true),
       ("Battlefield 2042", NULL, true, true);

INSERT INTO users (firstName, lastName, userName, passwordHash, email, bio)
VALUES 
    ("Jack", "Phillips", "Jack41400", 12345, "jack@email.com", "I like video games"),
	("Ayoub", "Bility", "bilityA", 12345, "Ayoub@email.com", "I like video games"),
    ("Isain", "Ibarra", "Isain1", 12345, "isain@email.com", "I like video games");
